void* jumpTable[] = {
    &&OPCODE_NOP,

    &&OPCODE_MOV,
    &&OPCODE_CPY,
    &&OPCODE_VAR,
    &&OPCODE_LOC,
    &&OPCODE_ALLC,
    &&OPCODE_PUSH,
    &&OPCODE_POP,
    &&OPCODE_LTOF,
    &&OPCODE_FTOL,
    
    &&OPCODE_ADD,
    &&OPCODE_SUB,
    &&OPCODE_MUL,
    &&OPCODE_DIV,
    &&OPCODE_MOD,
    &&OPCODE_INC,
    &&OPCODE_DEC,
    &&OPCODE_ADDF,
    &&OPCODE_SUBF,
    &&OPCODE_MULF,
    &&OPCODE_DIVF,
    &&OPCODE_INCF,
    &&OPCODE_DECF,
    
    &&OPCODE_EQ,
    &&OPCODE_NE,
    &&OPCODE_GT,
    &&OPCODE_LT,
    &&OPCODE_EQF,
    &&OPCODE_NEF,
    &&OPCODE_GTF,
    &&OPCODE_LTF,
    
    &&OPCODE_AND,
    &&OPCODE_OR,
    &&OPCODE_NOT,
    
    &&OPCODE_JMP,
    &&OPCODE_JC,
    &&OPCODE_LBL,
    &&OPCODE_CALL,
    &&OPCODE_RET,
    
    &&OPCODE_EXIT,
    &&OPCODE_OPEN,
    &&OPCODE_CLOSE,
    &&OPCODE_READ,
    &&OPCODE_WRITE,
    
    &&OPCODE_SRC,
    &&OPCODE_PRINT_NUM,
    &&OPCODE_HALT,
};
